modLoader="javafml"
loaderVersion="[43,)"
license="Not specified"

[[mods]]
modId="minecraftnewversionmod"
version="1.0.0"
displayName="minecraftnewversionmod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Administrator, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.minecraftnewversionmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration
